<?php

namespace UserManagement\UserMgtBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserContactRepository extends EntityRepository
{
}
