user_management_user_mgt_homepage:
    path:     /
    defaults: { _controller: UserManagementUserMgtBundle:Default:index }

login_check:
    path:   /user/login_check

login:
    pattern:   /login
    defaults:  { _controller: UserManagementUserMgtBundle:Default:login }

test_security:
    pattern: /user
    defaults: {_controller: UserManagementUserMgtBundle:Default:index }

logout:
    pattern: /user/logout

signup:
    pattern:   /signup
    defaults:  { _controller: UserManagementUserMgtBundle:Default:signup }
    requirements:
        _method:  GET|POST