user_management_user_mgt_homepage:
    path:     /
    defaults: { _controller: UserManagementUserMgtBundle:Default:welcome }

login_check:
    path:   /user/login_check

login:
    pattern:   /login
    defaults:  { _controller: UserManagementUserMgtBundle:Default:login }

home:
    pattern: /user
    defaults: {_controller: UserManagementUserMgtBundle:Default:index }

logout:
    pattern: /user/logout

signup:
    pattern:   /signup
    defaults:  { _controller: UserManagementUserMgtBundle:Default:signup }
    requirements:
        _method:  GET|POST

profile:
    pattern: /user/profile
    defaults: {_controller: UserManagementUserMgtBundle:Default:profile }
    requirements:
        _method:  GET|POST

changepass:
    pattern: /user/change-password
    defaults: {_controller: UserManagementUserMgtBundle:Default:changepass }
    requirements:
        _method:  GET|POST

confirm:
    pattern: /confirm/{key}/{date}
    defaults: {_controller: UserManagementUserMgtBundle:Default:confirmAccount}
    requirements:
        _method:  GET|POST

forgotpass:
    pattern:   /forgotpass
    defaults:  { _controller: UserManagementUserMgtBundle:Default:forgotpass }
    requirements:
        _method:  GET|POST

reset:
    pattern:   /reset/{key}/{time}
    defaults:  { _controller: UserManagementUserMgtBundle:Default:resetConfirm }
    requirements:
        _method:  GET|POST

resetpass:
    pattern:   /resetpass
    defaults:  { _controller: UserManagementUserMgtBundle:Default:resetPass }
    requirements:
        _method:  GET|POST