user_management_user_mgt_homepage:
    path:     /
    defaults: { _controller: UserManagementUserMgtBundle:Default:login }

login_check:
    path:   /user/login_check

login:
    pattern:   /login
    defaults:  { _controller: UserManagementUserMgtBundle:Default:login }

home:
    pattern: /user
    defaults: {_controller: UserManagementUserMgtBundle:Default:index }

logout:
    pattern: /user/logout

signup:
    pattern:   /signup
    defaults:  { _controller: UserManagementUserMgtBundle:Default:signup }
    requirements:
        _method:  GET|POST

profile:
    pattern: /user/profile
    defaults: {_controller: UserManagementUserMgtBundle:Default:profile }
    requirements:
        _method:  GET|POST

changepass:
    pattern: /user/change-password
    defaults: {_controller: UserManagementUserMgtBundle:Default:changepass }
    requirements:
        _method:  GET|POST