security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        UserManagement\UserMgtBundle\Entity\User:
            algorithm:        sha256
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, main]
        in_memory:
            memory:
                users:
                    user@user.com:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin@admin.com: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity: { class: UserManagementUserMgtBundle:User, property: email }

    firewalls:
        login_firewall:
            pattern: ^/login$
            security: false
        secured_area:
            provider: main
            pattern:    ^/user
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: /user
                csrf_provider: form.csrf_provider
            logout:
                path:   logout
                target: login
            #anonymous: ~
            http_basic: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/user, roles: ROLE_USER }